const productos = [
    {
        id: 1,
        marca: "Adidas",
        modelo: "Adizero",
        precio: 120,
        img: "./assets/img/adizero.jpg",
        cantidad: 1,
    },
    {
        id: 2,
        marca: "Adidas",
        modelo: "Ultraboost",
        precio: 265,
        img: "./assets/img/ultraboost.jpg",
        cantidad: 1,
    },
    {
        id: 3,
        marca: "Adidas",
        modelo: "Response",
        precio: 129,
        img: "./assets/img/response.jpg",
        cantidad: 1,
    },
    {
        id: 4,
        marca: "Adidas",
        modelo: "Superstar",
        precio: 180,
        img: "./assets/img/superstar.jpg",
        cantidad: 1,
    },
    {
        id: 5,
        marca: "Nike",
        modelo: "Vomero",
        precio: 139,
        img: "./assets/img/vomero.jpg",
        cantidad: 1,
    },
    {
        id: 6,
        marca: "Nike",
        modelo: "Pegasus",
        precio: 209,
        img: "./assets/img/pegasus.jpg",
        cantidad: 1,
    },
    {
        id: 7,
        marca: "Nike",
        modelo: "Precision VI",
        precio: 140,
        img: "./assets/img/precision.jpg",
        cantidad: 1,
    },
    {
        id: 8,
        marca: "Nike",
        modelo: "Air Max",
        precio: 169,
        img: "./assets/img/airmax.jpg",
        cantidad: 1,
    },
    {
        id: 9,
        marca: "Puma",
        modelo: "Deviate Nitro 2",
        precio: 99,
        img: "./assets/img/deviate.jpg",
        cantidad: 1,
    },
    {
        id: 10,
        marca: "Puma",
        modelo: "Magnify Nitro 2",
        precio: 209,
        img: "./assets/img/magnify.jpg",
        cantidad: 1,
    },
    {
        id: 11,
        marca: "Puma",
        modelo: "Velocity Nitro 3",
        precio: 79,
        img: "./assets/img/velocity.jpg",
        cantidad: 1,
    },
    {
        id: 12,
        marca: "Puma",
        modelo: "Ca Pro Classics",
        precio: 145,
        img: "./assets/img/classic.jpg",
        cantidad: 1,
    },
    {
        id: 13,
        marca: "Saucony",
        modelo: "Axon 2",
        precio: 120,
        img: "./assets/img/axon.jpg",
        cantidad: 1,
    },
    {
        id: 14,
        marca: "Saucony",
        modelo: "Endorphin Speed 3",
        precio: 265,
        img: "./assets/img/endorphin.jpg",
        cantidad: 1,
    },
    {
        id: 15,
        marca: "Saucony",
        modelo: "Endorphin Pro 3",
        precio: 129,
        img: "./assets/img/endorphin3.jpg",
        cantidad: 1,
    },
    {
        id: 16,
        marca: "Saucony",
        modelo: "Guide 15",
        precio: 180,
        img: "./assets/img/guide.jpg",
        cantidad: 1,
    },
];